name: Build & Release APK for Flutter Application

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'What to build'
        default: 'Android'
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '13'

      - uses: actions/cache@v3
        with:
          path: |
            **/flutter/.pub
            **/flutter/bin
            **/flutter/packages
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-  # Matches any previous cache key

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
          architecture: x64

      - run: if cd flutter; then git pull && cd ..; else git clone git clone "https://github.com/${{ secrets.OWNER }}/${{ secrets.REPO }}.git"; fi && cd flutter
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build apk --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          owner: ${{ secrets.OWNER }}
          repo: ${{ secrets.REPO }}
          # tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          tag: v1.0.0