name: Build & Release APK for Flutter Application
on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:
    inputs:
      name:
        description: 'What to build'
        default: 'Android'
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git clone "https://farflungai:$TOKEN@github.com/$OWNER/$REPO.git" tmp
      - shell: bash
        env:
          NOTIFY_ENDPOINT: ${{ secrets.NOTIFY_ENDPOINT }}
        run: |
          cd tmp
          COMMIT_MESSAGE=$(git log --pretty=format:"%s" -n 1)
          BUILD_NAME="v$(date +'%Y-%m-%d::%H:%M:%S')"
          if [[ -z "$COMMIT_MESSAGE" ]]; then
            echo "No commit message found"
          else
            echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
            echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
            curl --location "$NOTIFY_ENDPOINT" \
              --header 'Content-Type: application/json' \
              --data "{ \"message\": \"New commit: $COMMIT_MESSAGE\" }"
          fi
      - run: mv tmp/* .
      - shell: bash
        env:
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.OVERRIDE_PACKAGE }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          cd packages
          git clone "https://farflungai:$TOKEN@github.com/$OWNER/flutter_$REPO.git" $REPO
          cd ..
          echo "dependency_overrides:"       > pubspec_overrides.yaml
          echo "  $REPO:"                   >> pubspec_overrides.yaml
          echo "    path: packages/$REPO"   >> pubspec_overrides.yaml
      # - name: Update version in YAML
      #   run: sed -i 's/path: ../path: packages/g' pubspec.yaml
      - name: create pubspec_overrides.yaml
        working-directory: flutter_packages/packages/flutter_markdown
        run: |
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: actions/cache@v3
        with:
          path: |
            **/flutter/.pub
            **/flutter/bin
            **/flutter/packages
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-  # Matches any previous cache key

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
          cache: true
          architecture: x64
      # - shell: bash
      #   env:
      #     OWNER: ${{ secrets.OWNER }}
      #     REPO: ${{ secrets.REPO }}
      #     TOKEN: ${{ secrets.TOKEN }}
      #   run: |
      #     if cd flutter; then git pull && cd ..; else git clone "https://farflungai:$TOKEN@github.com/$OWNER/$REPO.git" && cd flutter; fi
      # - run: rm -rf flutter
      - run: flutter pub get
      - run: flutter --version
      # - run: flutter build apk --release
      - run: flutter build apk --split-per-abi --target-platform android-arm64 --build-name $BUILD_NAME
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          owner: ${{ secrets.OWNER }}
          repo: ${{ secrets.REPO }}
          # tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          tag: v1.0.0
      - shell: bash
        env:
          NOTIFY_ENDPOINT: ${{ secrets.NOTIFY_ENDPOINT }}
        run: |
          curl --location "$NOTIFY_ENDPOINT" \
            --header 'Content-Type: application/json' \
            --data "{ \"message\": \"Release ($BUILD_NAME) is ready for download\" }"
      